/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NumbersToWords;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        NumbersToWords classUnderTest = new NumbersToWords();
        assertEquals("One", classUnderTest.convert(1));
        assertEquals(null, classUnderTest.convert(0));
    }
}
